name: master
channels:
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - openssl=1.1.1g=he774522_0
  - pip=20.0.2=py37_1
  - python=3.7.6=h60c2a47_2
  - setuptools=45.2.0=py37_0
  - sqlite=3.31.1=he774522_0
  - swig=3.0.12=h047fa9f_3
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - absl-py==0.9.0
    - astetik==1.9.9
    - astor==0.8.1
    - astroid==2.4.1
    - astunparse==1.6.3
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - cachetools==4.0.0
    - chances==0.1.9
    - chardet==3.0.4
    - colorama==0.4.3
    - cycler==0.10.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - entrypoints==0.3
    - flake8==3.7.9
    - future==0.18.2
    - gast==0.3.3
    - geonamescache==1.1.0
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - googleapis-common-protos==1.51.0
    - grpcio==1.27.2
    - gviz-api==1.9.0
    - h5py==2.10.0
    - idna==2.8
    - importlib-metadata==1.5.0
    - iprogress==0.4
    - ipykernel==5.1.4
    - ipython==7.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - isort==4.3.21
    - jedi==0.16.0
    - jinja2==2.11.1
    - joblib==0.14.1
    - json5==0.9.1
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.2
    - jupyterlab==1.2.6
    - jupyterlab-server==1.0.6
    - keras==2.3.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kerasplotlib==0.1.6
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.3
    - markdown==3.2.1
    - markupsafe==1.1.1
    - matplotlib==3.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - notebook==6.0.3
    - numpy==1.18.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - packaging==20.3
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.6.1
    - pathlib2==2.3.5
    - patsy==0.5.1
    - pickleshare==0.7.5
    - pillow==7.1.2
    - prometheus-client==0.7.1
    - promise==2.3
    - prompt-toolkit==3.0.3
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.5.2
    - pylint==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pywin32==227
    - pywinpty==0.5.7
    - pyyaml==5.3.1
    - pyzmq==18.1.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.10.1
    - send2trash==1.5.0
    - six==1.14.0
    - sklearn==0.0
    - statsmodels==0.11.1
    - tensorboard==2.2.1
    - tensorboard-plugin-profile==2.2.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-datasets==3.1.0
    - tensorflow-estimator==2.2.0
    - tensorflow-gpu==2.2.0
    - tensorflow-gpu-estimator==2.2.0
    - tensorflow-hub==0.8.0
    - tensorflow-metadata==0.21.2
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - toml==0.10.0
    - tornado==6.0.3
    - tqdm==4.46.0
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - urllib3==1.25.8
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - werkzeug==1.0.0
    - widgetsnbextension==3.5.1
    - wrangle==0.6.7
    - wrapt==1.12.0
    - zipp==3.0.0
prefix: C:\Users\lucas\Anaconda3\envs\master

